version: "3.8"

services:
  redis:
    image: redis
    command: redis-server --requirepass developer
    ports:
      - "6379:6379"
    volumes:
      - redis_data:/data
    restart: unless-stopped

volumes:
  postgres_data:
